version: '3'
services:
  server:
    build:
      context: ./weedvidio-backend
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    environment:
      NODE_ENV: production
      PORT: 8000
    networks: 
      - net
  caddy:
    image: caddy:2.3.0-alpine
    restart: unless-stopped
    ports: 
      - "80:80"
      - "443:443"
    volumes:
      - $PWD/caddy/Caddyfile.dev:/etc/caddy/Caddyfile
    networks: 
      - net
networks: 
  net:
    driver: bridge