version: '3'
services:
  web:
    build: .
    ports:
      - "3000:3000"
    environment:
      NODE_ENV: production
      PORT: 3000
      REACT_APP_PROD_BACKEND: http://localhost:8000
      REACT_APP_LOCAL_BACKEND: http://localhost:8000
  
