version: '2'
services:
  server:
    build: .
    ports:
    	- "8000:8000"
    environment:
		NODE_ENV: production
		PORT: 8000
		FRONTEND_URL_LOCAL: http://localhost:5000
		FRONTEND_URL: http://10.0.0.22:5000
		FRONTEND_URL_DEV: http://localhost:3000
